
server:
  port: 8888

spring:
  application:
    name: bootcamp-avengers-configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jgsistem/bootcamp-avengers-configserver
          default-label: main
          timeout: 10
